In [1]:
import pandas as pd

In [13]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "customer_name": ["John", "Mary", "David", "Sarah"]
})

In [14]:
customers

   customer_id customer_name
0            1          John
1            2          Mary
2            3         David
3            4         Sarah

In [17]:
orders = pd.DataFrame({
    "customer_id": [1, 2, 1, 3],
    "order_amount": [500, 700, 300, 900]
})

In [5]:
orders

   order_id  order_amount
0         1           500
1         2           700
2         1           300
3         3           900

In [21]:
merged_df = pd.merge(
    customers,
    orders,
    on="customer_id"
)

In [22]:
merged_df

   customer_id customer_name  order_amount
0            1          John           500
1            1          John           300
2            2          Mary           700
3            3         David           900

In [23]:
left_join_df = pd.merge(
    customers,
    orders,
    on = "customer_id",
    how = "left"
)

In [24]:
left_join_df

   customer_id customer_name  order_amount
0            1          John         500.0
1            1          John         300.0
2            2          Mary         700.0
3            3         David         900.0
4            4         Sarah           NaN

In [25]:
right_join_df = pd.merge(
    customers,
    orders,
    on = "customer_id",
    how = "right"
)

In [26]:
right_join_df

   customer_id customer_name  order_amount
0            1          John           500
1            2          Mary           700
2            1          John           300
3            3         David           900

In [27]:
outer_join_df = pd.merge(
    customers,
    orders,
    on = "customer_id",
    how = "outer"
)

In [28]:
outer_join_df

   customer_id customer_name  order_amount
0            1          John         500.0
1            1          John         300.0
2            2          Mary         700.0
3            3         David         900.0
4            4         Sarah           NaN

In [29]:
orders_1 = pd.DataFrame({
    "customer_id": [1,2],
    "order_amount" : [500, 700] 
})

orders_2 = pd.DataFrame({
    "customer_id": [3, 4],
    "order_amount" : [900, 1200]
})

In [30]:
combined_orders = pd.concat(
    [orders_1,orders_2]
)

combined_orders

   customer_id  order_amount
0            1           500
1            2           700
0            3           900
1            4          1200

In [31]:
avg_order = orders['order_amount'].mean()

In [32]:
orders[orders['order_amount'] > avg_order]

   customer_id  order_amount
1            2           700
3            3           900

In [33]:
avg_order

np.float64(600.0)

In [34]:
orders['customer_total_sales'] = (
    orders.groupby('customer_id')['order_amount'].transform('sum')
)

In [35]:
orders

   customer_id  order_amount  customer_total_sales
0            1           500                   800
1            2           700                   700
2            1           300                   800
3            3           900                   900