# Day 1 - Advanced Pandas Operations

Focus:
- Advanced filtering
- Multi-index
- GroupBy deep dives
- Pivot / Pivot tables
- Apply vs Vectorization

Mini Challenge:
Messy Sales Dataset Analysis

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
print ("Environment is set up and ready to go!")

Environment is set up and ready to go!

In [4]:
df = pd.read_csv("../data/SuperStoreOrders.csv")

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  str
 1   order_date      51290 non-null  str
 2   ship_date       51290 non-null  str
 3   ship_mode       51290 non-null  str
 4   customer_name   51290 non-null  str
 5   segment         51290 non-null  str
 6   state           51290 non-null  str
 7   country         51290 non-null  str
 8   market          51290 non-null  str
 9   region          51290 non-null  str
 10  product_id      51290 non-null  str
 11  category        51290 non-null  str
 12  sub_category    51290 non-null  str
 13  product_name    51290 non-null  str
 14  sales           51290 non-null  str
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  str
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), str(16)
memory usage: 8.2 MB

In [6]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [7]:
df.shape

(51290, 21)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  str
 1   order_date      51290 non-null  str
 2   ship_date       51290 non-null  str
 3   ship_mode       51290 non-null  str
 4   customer_name   51290 non-null  str
 5   segment         51290 non-null  str
 6   state           51290 non-null  str
 7   country         51290 non-null  str
 8   market          51290 non-null  str
 9   region          51290 non-null  str
 10  product_id      51290 non-null  str
 11  category        51290 non-null  str
 12  sub_category    51290 non-null  str
 13  product_name    51290 non-null  str
 14  sales           51290 non-null  str
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  str
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), str(16)
memory usage: 8.2 MB

In [9]:
df

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.1400,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.0360,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.6400,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.0550,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.7700,4.70,Medium,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,CA-2014-115427,31-12-2014,4/1/2015,Standard Class,Erica Bern,Corporate,California,United States,US,West,...,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",14,2,0.2,4.5188,0.89,Medium,2014
51286,MO-2014-2560,31-12-2014,5/1/2015,Standard Class,Liz Preis,Consumer,Souss-Massa-Draâ,Morocco,Africa,Africa,...,Office Supplies,Binders,"Wilson Jones Hole Reinforcements, Clear",4,1,0.0,0.4200,0.49,Medium,2014
51287,MX-2014-110527,31-12-2014,2/1/2015,Second Class,Charlotte Melton,Consumer,Managua,Nicaragua,LATAM,Central,...,Office Supplies,Labels,"Hon Color Coded Labels, 5000 Label Set",26,3,0.0,12.3600,0.35,Medium,2014
51288,MX-2014-114783,31-12-2014,6/1/2015,Standard Class,Tamara Dahlen,Consumer,Chihuahua,Mexico,LATAM,North,...,Office Supplies,Labels,"Hon Legal Exhibit Labels, Alphabetical",7,1,0.0,0.5600,0.20,Medium,2014
51289,CA-2014-156720,31-12-2014,4/1/2015,Standard Class,Jill Matthias,Consumer,Colorado,United States,US,West,...,Office Supplies,Fasteners,Bagged Rubber Bands,3,3,0.2,-0.6048,0.17,Medium,2014

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  str
 1   order_date      51290 non-null  str
 2   ship_date       51290 non-null  str
 3   ship_mode       51290 non-null  str
 4   customer_name   51290 non-null  str
 5   segment         51290 non-null  str
 6   state           51290 non-null  str
 7   country         51290 non-null  str
 8   market          51290 non-null  str
 9   region          51290 non-null  str
 10  product_id      51290 non-null  str
 11  category        51290 non-null  str
 12  sub_category    51290 non-null  str
 13  product_name    51290 non-null  str
 14  sales           51290 non-null  str
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  str
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), str(16)
memory usage: 8.2 MB

In [11]:
df

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.1400,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.0360,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.6400,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.0550,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.7700,4.70,Medium,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,CA-2014-115427,31-12-2014,4/1/2015,Standard Class,Erica Bern,Corporate,California,United States,US,West,...,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",14,2,0.2,4.5188,0.89,Medium,2014
51286,MO-2014-2560,31-12-2014,5/1/2015,Standard Class,Liz Preis,Consumer,Souss-Massa-Draâ,Morocco,Africa,Africa,...,Office Supplies,Binders,"Wilson Jones Hole Reinforcements, Clear",4,1,0.0,0.4200,0.49,Medium,2014
51287,MX-2014-110527,31-12-2014,2/1/2015,Second Class,Charlotte Melton,Consumer,Managua,Nicaragua,LATAM,Central,...,Office Supplies,Labels,"Hon Color Coded Labels, 5000 Label Set",26,3,0.0,12.3600,0.35,Medium,2014
51288,MX-2014-114783,31-12-2014,6/1/2015,Standard Class,Tamara Dahlen,Consumer,Chihuahua,Mexico,LATAM,North,...,Office Supplies,Labels,"Hon Legal Exhibit Labels, Alphabetical",7,1,0.0,0.5600,0.20,Medium,2014
51289,CA-2014-156720,31-12-2014,4/1/2015,Standard Class,Jill Matthias,Consumer,Colorado,United States,US,West,...,Office Supplies,Fasteners,Bagged Rubber Bands,3,3,0.2,-0.6048,0.17,Medium,2014

In [12]:
df[['sales']]

      sales
0       408
1       120
2        66
3        45
4       114
...     ...
51285    14
51286     4
51287    26
51288     7
51289     3

[51290 rows x 1 columns]

In [13]:
df.describe()

           quantity      discount        profit  shipping_cost          year
count  51290.000000  51290.000000  51290.000000   51290.000000  51290.000000
mean       3.476545      0.142908     28.641740      26.375915   2012.777208
std        2.278766      0.212280    174.424113      57.296804      1.098931
min        1.000000      0.000000  -6599.978000       0.000000   2011.000000
25%        2.000000      0.000000      0.000000       2.610000   2012.000000
50%        3.000000      0.000000      9.240000       7.790000   2013.000000
75%        5.000000      0.200000     36.810000      24.450000   2014.000000
max       14.000000      0.850000   8399.976000     933.570000   2014.000000

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  str
 1   order_date      51290 non-null  str
 2   ship_date       51290 non-null  str
 3   ship_mode       51290 non-null  str
 4   customer_name   51290 non-null  str
 5   segment         51290 non-null  str
 6   state           51290 non-null  str
 7   country         51290 non-null  str
 8   market          51290 non-null  str
 9   region          51290 non-null  str
 10  product_id      51290 non-null  str
 11  category        51290 non-null  str
 12  sub_category    51290 non-null  str
 13  product_name    51290 non-null  str
 14  sales           51290 non-null  str
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  str
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), str(16)
memory usage: 8.2 MB

In [15]:
df[['order_id', 'order_date', 'customer_name']]

              order_id  order_date     customer_name
0         AG-2011-2040    1/1/2011   Toby Braunhardt
1        IN-2011-47883    1/1/2011       Joseph Holt
2         HU-2011-1220    1/1/2011     Annie Thurman
3      IT-2011-3647632    1/1/2011      Eugene Moren
4        IN-2011-47883    1/1/2011       Joseph Holt
...                ...         ...               ...
51285   CA-2014-115427  31-12-2014        Erica Bern
51286     MO-2014-2560  31-12-2014         Liz Preis
51287   MX-2014-110527  31-12-2014  Charlotte Melton
51288   MX-2014-114783  31-12-2014     Tamara Dahlen
51289   CA-2014-156720  31-12-2014     Jill Matthias

[51290 rows x 3 columns]

In [16]:
df.shae

AttributeError: 'DataFrame' object has no attribute 'shae'

In [ ]:
df.shape

(51290, 21)

In [ ]:
df

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.1400,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.0360,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.6400,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.0550,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.7700,4.70,Medium,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,CA-2014-115427,31-12-2014,4/1/2015,Standard Class,Erica Bern,Corporate,California,United States,US,West,...,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",14,2,0.2,4.5188,0.89,Medium,2014
51286,MO-2014-2560,31-12-2014,5/1/2015,Standard Class,Liz Preis,Consumer,Souss-Massa-Draâ,Morocco,Africa,Africa,...,Office Supplies,Binders,"Wilson Jones Hole Reinforcements, Clear",4,1,0.0,0.4200,0.49,Medium,2014
51287,MX-2014-110527,31-12-2014,2/1/2015,Second Class,Charlotte Melton,Consumer,Managua,Nicaragua,LATAM,Central,...,Office Supplies,Labels,"Hon Color Coded Labels, 5000 Label Set",26,3,0.0,12.3600,0.35,Medium,2014
51288,MX-2014-114783,31-12-2014,6/1/2015,Standard Class,Tamara Dahlen,Consumer,Chihuahua,Mexico,LATAM,North,...,Office Supplies,Labels,"Hon Legal Exhibit Labels, Alphabetical",7,1,0.0,0.5600,0.20,Medium,2014
51289,CA-2014-156720,31-12-2014,4/1/2015,Standard Class,Jill Matthias,Consumer,Colorado,United States,US,West,...,Office Supplies,Fasteners,Bagged Rubber Bands,3,3,0.2,-0.6048,0.17,Medium,2014

In [ ]:
df['sales'].max()

'999'

In [ ]:
df['sales'].min()

'0'

In [ ]:
df['sales'].dtypes

In [ ]:
df['sales'] = pd.to_numeric(df['sales'], errors = 'coerce')

In [ ]:
df['sales'].dtypes

dtype('float64')

In [ ]:
df['sales'].mean()

np.float64(161.01783806000822)

In [18]:
df['sales'].mean()

TypeError: Cannot perform reduction 'mean' with string dtype

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [order_id, order_date, ship_date, ship_mode, customer_name, segment, state, country, market, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit, shipping_cost, order_priority, year]
Index: []

[0 rows x 21 columns]

In [19]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [20]:
df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name',
       'segment', 'state', 'country', 'market', 'region', 'product_id',
       'category', 'sub_category', 'product_name', 'sales', 'quantity',
       'discount', 'profit', 'shipping_cost', 'order_priority', 'year'],
      dtype='str')

In [21]:
df.dtypes

order_id              str
order_date            str
ship_date             str
ship_mode             str
customer_name         str
segment               str
state                 str
country               str
market                str
region                str
product_id            str
category              str
sub_category          str
product_name          str
sales                 str
quantity            int64
discount          float64
profit            float64
shipping_cost     float64
order_priority        str
year                int64
dtype: object

In [22]:
high_sales = df[df['sales']>1000]

TypeError: '>' not supported between instances of 'str' and 'int'

In [27]:
df['sales'] = pd.to_numeric(df['sales'], errors = 'coerce')

In [29]:
high_sales = df[df['sales']>1000]

In [25]:
df.dtypes

order_id              str
order_date            str
ship_date             str
ship_mode             str
customer_name         str
segment               str
state                 str
country               str
market                str
region                str
product_id            str
category              str
sub_category          str
product_name          str
sales                 str
quantity            int64
discount          float64
profit            float64
shipping_cost     float64
order_priority        str
year                int64
sale              float64
dtype: object

In [30]:
high_sales.head()

Empty DataFrame
Columns: [order_id, order_date, ship_date, ship_mode, customer_name, segment, state, country, market, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit, shipping_cost, order_priority, year, sale]
Index: []

[0 rows x 22 columns]

In [31]:
high_sales

Empty DataFrame
Columns: [order_id, order_date, ship_date, ship_mode, customer_name, segment, state, country, market, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit, shipping_cost, order_priority, year, sale]
Index: []

[0 rows x 22 columns]

In [32]:
df['sales'].max()

np.float64(999.0)

In [33]:
df['sales'].describe()

count    48660.000000
mean       161.017838
std        201.092519
min          0.000000
25%         29.000000
50%         77.000000
75%        208.000000
max        999.000000
Name: sales, dtype: float64

In [34]:
high_sales = df[df['sale']>500]

In [35]:
high_sales

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,sale
8,ID-2011-80230,3/1/2011,9/1/2011,Standard Class,Ken Lonsdale,Consumer,Auckland,New Zealand,APAC,Oceania,...,Copiers,"Hewlett Wireless Fax, Laser",912.0,4,0.40,-319.464,107.10,Low,2011,912.0
9,IZ-2011-4680,3/1/2011,7/1/2011,Standard Class,Lindsay Williams,Corporate,Ninawa,Iraq,EMEA,EMEA,...,Chairs,"Novimex Swivel Stool, Set of Two",667.0,4,0.00,253.320,81.26,High,2011,667.0
12,ES-2011-4869686,3/1/2011,7/1/2011,Standard Class,Dorothy Dickinson,Consumer,England,United Kingdom,EU,North,...,Bookcases,"Dania Corner Shelving, Traditional",854.0,7,0.00,290.430,12.56,Medium,2011,854.0
59,CA-2011-167199,7/1/2011,11/1/2011,Standard Class,Maria Etezadi,Home Office,Kentucky,United States,US,South,...,Binders,Ibico Hi-Tech Manual Binding System,610.0,2,0.00,274.491,88.07,High,2011,610.0
64,ES-2011-5433855,7/1/2011,8/1/2011,First Class,Dave Poirier,Corporate,Provence-Alpes-Côte d'Azur,France,EU,Central,...,Storage,"Smead Lockers, Industrial",716.0,4,0.10,143.160,32.46,Medium,2011,716.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51230,RS-2014-1460,31-12-2014,2/1/2015,Second Class,Peter Bühler,Consumer,Bashkortostan,Russia,EMEA,EMEA,...,Copiers,"Hewlett Personal Copier, Laser",866.0,6,0.00,51.840,138.18,High,2014,866.0
51232,ES-2014-3458802,31-12-2014,5/1/2015,Standard Class,John Grady,Corporate,England,United Kingdom,EU,North,...,Phones,"Motorola Audio Dock, VoIP",867.0,5,0.00,251.400,53.16,Medium,2014,867.0
51234,ES-2014-1695428,31-12-2014,2/1/2015,Second Class,Rick Duston,Consumer,Lower Normandy,France,EU,Central,...,Storage,"Fellowes Lockers, Wire Frame",557.0,3,0.10,216.720,51.79,Medium,2014,557.0
51236,ES-2014-5281275,31-12-2014,4/1/2015,Second Class,Shirley Schmidt,Home Office,Madrid,Spain,EU,South,...,Copiers,"Hewlett Copy Machine, Color",530.0,2,0.00,180.240,48.00,Medium,2014,530.0
51239,ID-2014-54442,31-12-2014,4/1/2015,Standard Class,Muhammed Yedwab,Corporate,National Capital,Philippines,APAC,Southeast Asia,...,Copiers,"Hewlett Copy Machine, Laser",685.0,4,0.35,-63.234,42.92,Medium,2014,685.0

In [36]:
high_sales.shape

(4112, 22)

In [38]:
high_sales_consumer = df[(df['sales']>500) & (df['segment'] == 'Consumer')]

In [40]:
high_sales_consumer

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,sale
8,ID-2011-80230,3/1/2011,9/1/2011,Standard Class,Ken Lonsdale,Consumer,Auckland,New Zealand,APAC,Oceania,...,Copiers,"Hewlett Wireless Fax, Laser",912.0,4,0.40,-319.4640,107.10,Low,2011,912.0
12,ES-2011-4869686,3/1/2011,7/1/2011,Standard Class,Dorothy Dickinson,Consumer,England,United Kingdom,EU,North,...,Bookcases,"Dania Corner Shelving, Traditional",854.0,7,0.00,290.4300,12.56,Medium,2011,854.0
85,IT-2011-4546695,8/1/2011,14-01-2011,Standard Class,Darren Powers,Consumer,Midi-Pyrénées,France,EU,Central,...,Bookcases,"Ikea Classic Bookcase, Metal",987.0,6,0.60,-1011.6360,65.64,Medium,2011,987.0
128,IN-2011-39308,11/1/2011,18-01-2011,Standard Class,David Flashing,Consumer,Jawa Barat,Indonesia,APAC,Southeast Asia,...,Phones,"Apple Audio Dock, VoIP",554.0,4,0.17,40.0536,42.43,Medium,2011,554.0
162,EG-2011-4270,13-01-2011,18-01-2011,Standard Class,Roger Demir,Consumer,Aswan,Egypt,Africa,Africa,...,Storage,"Smead Lockers, Blue",794.0,4,0.00,134.8800,76.60,Medium,2011,794.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51052,EG-2014-8040,29-12-2014,2/1/2015,Standard Class,Darrin Martin,Consumer,Al Qahirah,Egypt,Africa,Africa,...,Accessories,"Logitech Memory Card, Erganomic",607.0,6,0.00,12.0600,38.61,Medium,2014,607.0
51057,ID-2014-48828,29-12-2014,2/1/2015,Standard Class,Karl Braun,Consumer,Jawa Barat,Indonesia,APAC,Southeast Asia,...,Copiers,"HP Personal Copier, Color",585.0,5,0.07,194.7945,29.71,Medium,2014,585.0
51162,ES-2014-5329048,30-12-2014,4/1/2015,Standard Class,Zuschuss Donatelli,Consumer,Upper Normandy,France,EU,Central,...,Tables,"Barricks Conference Table, Rectangular",588.0,1,0.35,-27.1575,36.25,Medium,2014,588.0
51230,RS-2014-1460,31-12-2014,2/1/2015,Second Class,Peter Bühler,Consumer,Bashkortostan,Russia,EMEA,EMEA,...,Copiers,"Hewlett Personal Copier, Laser",866.0,6,0.00,51.8400,138.18,High,2014,866.0
51234,ES-2014-1695428,31-12-2014,2/1/2015,Second Class,Rick Duston,Consumer,Lower Normandy,France,EU,Central,...,Storage,"Fellowes Lockers, Wire Frame",557.0,3,0.10,216.7200,51.79,Medium,2014,557.0

In [43]:
tech_sales = df.query("sales > 500 and category == 'Technology'")

In [44]:
tech_sales

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,sale
8,ID-2011-80230,3/1/2011,9/1/2011,Standard Class,Ken Lonsdale,Consumer,Auckland,New Zealand,APAC,Oceania,...,Copiers,"Hewlett Wireless Fax, Laser",912.0,4,0.40,-319.4640,107.10,Low,2011,912.0
67,CA-2011-167199,7/1/2011,11/1/2011,Standard Class,Maria Etezadi,Home Office,Kentucky,United States,US,South,...,Phones,Wireless Extenders zBoost YX545 SOHO Signal Bo...,756.0,4,0.00,204.1092,13.82,High,2011,756.0
102,HU-2011-1380,10/1/2011,10/1/2011,Same Day,Elpida Rittenbach,Corporate,Budapest,Hungary,EMEA,EMEA,...,Copiers,"Canon Ink, Laser",589.0,4,0.00,276.6000,114.15,Critical,2011,589.0
128,IN-2011-39308,11/1/2011,18-01-2011,Standard Class,David Flashing,Consumer,Jawa Barat,Indonesia,APAC,Southeast Asia,...,Phones,"Apple Audio Dock, VoIP",554.0,4,0.17,40.0536,42.43,Medium,2011,554.0
129,IN-2011-79761,11/1/2011,16-01-2011,Standard Class,Steve Carroll,Home Office,Calabarzon,Philippines,APAC,Southeast Asia,...,Copiers,"Sharp Wireless Fax, Color",697.0,3,0.35,-343.0980,40.16,Medium,2011,697.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51057,ID-2014-48828,29-12-2014,2/1/2015,Standard Class,Karl Braun,Consumer,Jawa Barat,Indonesia,APAC,Southeast Asia,...,Copiers,"HP Personal Copier, Color",585.0,5,0.07,194.7945,29.71,Medium,2014,585.0
51230,RS-2014-1460,31-12-2014,2/1/2015,Second Class,Peter Bühler,Consumer,Bashkortostan,Russia,EMEA,EMEA,...,Copiers,"Hewlett Personal Copier, Laser",866.0,6,0.00,51.8400,138.18,High,2014,866.0
51232,ES-2014-3458802,31-12-2014,5/1/2015,Standard Class,John Grady,Corporate,England,United Kingdom,EU,North,...,Phones,"Motorola Audio Dock, VoIP",867.0,5,0.00,251.4000,53.16,Medium,2014,867.0
51236,ES-2014-5281275,31-12-2014,4/1/2015,Second Class,Shirley Schmidt,Home Office,Madrid,Spain,EU,South,...,Copiers,"Hewlett Copy Machine, Color",530.0,2,0.00,180.2400,48.00,Medium,2014,530.0
51239,ID-2014-54442,31-12-2014,4/1/2015,Standard Class,Muhammed Yedwab,Corporate,National Capital,Philippines,APAC,Southeast Asia,...,Copiers,"Hewlett Copy Machine, Laser",685.0,4,0.35,-63.2340,42.92,Medium,2014,685.0

In [45]:
df.groupby('category')['sales'].sum()

category
Furniture          2406605.0
Office Supplies    2790258.0
Technology         2638265.0
Name: sales, dtype: float64

In [46]:
df.groupby("category")["sales"].sum().sort_values(ascending=False)

category
Office Supplies    2790258.0
Technology         2638265.0
Furniture          2406605.0
Name: sales, dtype: float64

In [47]:
df.groupby("category").agg({
    "sales": ["sum", "mean"],
    "profit": ["sum", "mean"]
})

                     sales                    profit
                       sum        mean           sum       mean
category
Furniture        2406605.0  270.222883  286782.25380  29.038300
Office Supplies  2790258.0   90.781429  518473.83430  16.578961
Technology       2638265.0  292.555445  663778.73318  65.454958

In [48]:
df.groupby(["category", "segment"])["sales"].sum()

category         segment
Furniture        Consumer       1226880.0
                 Corporate       755916.0
                 Home Office     423809.0
Office Supplies  Consumer       1454836.0
                 Corporate       823404.0
                 Home Office     512018.0
Technology       Consumer       1376402.0
                 Corporate       789941.0
                 Home Office     471922.0
Name: sales, dtype: float64

In [49]:
multi_sales = df.groupby(
    ["category", "segment"]
)["sales"].sum()

multi_sales

category         segment
Furniture        Consumer       1226880.0
                 Corporate       755916.0
                 Home Office     423809.0
Office Supplies  Consumer       1454836.0
                 Corporate       823404.0
                 Home Office     512018.0
Technology       Consumer       1376402.0
                 Corporate       789941.0
                 Home Office     471922.0
Name: sales, dtype: float64

In [50]:
pd.pivot_table(
    df,
    values="sales",
    index="category",
    aggfunc="sum"
)

                     sales
category
Furniture        2406605.0
Office Supplies  2790258.0
Technology       2638265.0

In [51]:
pd.pivot_table(
    df,
    values="sales",
    index="category",
    columns="segment",
    aggfunc="sum"
)

segment           Consumer  Corporate  Home Office
category
Furniture        1226880.0   755916.0     423809.0
Office Supplies  1454836.0   823404.0     512018.0
Technology       1376402.0   789941.0     471922.0

In [52]:
df["profit_status"] = np.where(
    df["profit"] > 0,
    "Profit",
    "Loss"
)

df[["profit", "profit_status"]].head()

    profit profit_status
0  106.140        Profit
1   36.036        Profit
2   29.640        Profit
3  -26.055          Loss
4   37.770        Profit